name: DevSecOps Pipeline

on:
  push:
    branches: [start ]

jobs:

# ---------------- BUILD ----------------

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21


    - name: Build Application
      run: mvn clean package -DskipTests


# ---------------- SAST SCAN ----------------

  sast-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - uses: actions/checkout@v4

    - name: Run CodeQL Scan
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - uses: github/codeql-action/analyze@v3


# ---------------- DEPENDENCY SCAN ----------------

  dependency-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - uses: actions/checkout@v4

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: bankapp
        path: .
        format: HTML


# ---------------- DOCKER BUILD ----------------

 


  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: dependency-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USER }}/bankapp:${{ github.sha }} -t ${{ vars.DOCKERHUB_USER }}/bankapp:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKERHUB_USER }}/bankapp:${{ github.sha }}
          format: table
          exit-code: 0        # Fail if vulnerabilities found
          severity: HIGH,CRITICAL

      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKERHUB_USER }}/bankapp:${{ github.sha }}
          docker push ${{ vars.DOCKERHUB_USER }}/bankapp:latest

# ---------------- DEPLOY ----------------

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-scan

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}

        script: |
          docker pull ${{ vars.DOCKERHUB_USER }}/bankapp:latest
          docker stop bankapp || true
          docker rm bankapp || true
          docker run -d -p 80:8080 --name bankapp ${{ vars.DOCKERHUB_USER }}/bankapp:latest